language: node_js
node_js:
  - "0.11"
  - "0.10"
  # DEV: Unsupported due to phonetic relying on `buffer.readUInt32LE`
  # https://github.com/TomFrost/node-phonetic/blob/0.1.0/lib/phonetic.js#L227
  # - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  - curl --location https://cdn.jsdelivr.net/gh/twolfson/fix-travis-ci@master/lib/install.sh | bash -s

notifications:
  email: false
